name: Deploy To Staging

on:
  push:
    tags:
      - staging
      - 'staging/*'

jobs:
  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag_name.outputs.tag_name }}
    steps:
      - name: Generate Tag Name
        id: tag_name
        run: echo "::set-output name=tag_name::$(date --rfc-3339=date)_${GITHUB_SHA::7}"

      - name: Create Tag
        uses: actions/github-script@master
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.tag_name.outputs.tag_name }}',
              sha: context.sha
            })

  sonarcloud:
      name: SonarCloud
      runs-on: ubuntu-latest
      needs: [create-tag]
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        - name: Use Node.js 20.x for build
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
        - run: npm i
        - run: npm run build --if-present
        - run: npm run test:cov